### ISSUE TITLE
Cannot compile project

### ISSUE THREAD

**Issue by draeger** [diffplug/matfilerw#1]
Maven gives the following errors when building the project with Java:
package edu.umd.cs.findbugs.annotations does not exist
cannot find symbol: class SuppressFBWarnings
cannot find symbol
  symbol:   class SuppressFBWarnings
  location: class com.jmatio.types.MLChar

It looks like some dependencies are missing. I had executed mvn dependency:resolve. Any hint is appreciated.

**Comment by nedtwigg** [comment]
Ahh, sorry.  The `pom.xml` and `project.clj` are both stale - I have just removed them.  Gradle is the up-to-date buildsystem.  You don't have to install anything to use it, just run `gradlew build`.  See the [contributing guide](https://github.com/diffplug/matfilerw/blob/master/CONTRIBUTING.md) for more info.
