### ISSUE TITLE
Breaking changes in 3.0.0

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/matfilerw#11]
Hi users!  We've found a bug that requires some breaking changes to fix.  Since we've gotta break compat anyway, this seems like a nice opportunity to clean up a few other warts.  I'm looking for comments on the things we're currently planning on breaking in 3.0.0:

* Fixed multidimensional array indexing (see [#10](https://github.com/diffplug/matfilerw/issues/10)).
	+ For arrays with dimension 1 or 2, there is no change.
	+ For arrays with dimension 3 and up, matfilerw 2.x did not order the dimensions in the column-major format used by MATLAB.  In 3.x forward, matfilerw uses the same column-major format as MATLAB.
* Complex and non-complex arrays now have separate methods.
	+ MLNumericArray has methods `getReal/setReal`, `getImaginary/setImaginary`, and `get/set`.
	+ In 2.x using the imaginary methods on a non-imaginary matrix would fail silently, and `get/set` were synonymous with `getReal/setReal`
	+ In 3.x, you can't use `getReal/setReal` on a non-complex matrix, and you can't use `get/set` on a complex matrix.

I'm tagging a few here who might be interested: @tmrn411, @mikaelgrev, @sinjax, @no-man-is-an-island, @gradusnikov.

**Comment by nedtwigg** [comment]
After a little more thought, I'm rethinking the `getReal/setReal`, `getImaginary/setImaginary`, and `get/set` division.  Complex arrays should really be a different type, but that's a bigger change than we can handle.  I think I'll remove the restrictions on `getReal/setReal`.

**Comment by tmrn411** [comment]
Just as point of reference, in Matlab real() and imag() work just fine on non-complex variables.  imag() just returns 0 in that case.  So I think the 2.x behavior is reasonable.

**Comment by nedtwigg** [comment]
Thanks for the info @tmrn411.  12858a6 makes sure that `imaginary` will return 0 for all non-complex arrays.

**Comment by nedtwigg** [comment]
Shipped 3.0.0
