### ISSUE TITLE
Access sparse matrix non-zero values and their indexes

### ISSUE THREAD

**Issue by elia-maracani** [diffplug/matfilerw#12]
Hi, 
I'll give you a brief introduction to the problem, hopefully it would help. :)
I'm doing a university project that requires importing a .mat sparse matrix in java and then multiply it with a dense vector.
I've found your library to do the former, and **la4j** the latter. 
Now, since I can't explicitly cast an `MLSparse` matrix (from your library), let's call it A, in a `CRSMatrix` (from **la4j**), let's call it B.
To do so I've created an empty sparse matrix with 

`CRSMatrix matrix = CRSMatrix.zero(400, 400)`

Here comes the problem. I now need to get all the values of each non-zero cell in the `MLSparse A` matrix and where those cells are located (they're row and col values).

I've seen there's a `private SortedMap<IndexMN, Double> real` field that does just that.
The problem is that, being it **private** there's no way to access it, as there is no method.

Am I doing this all wrong? Is it a supposed bevahior?
Any advice how to get this thing done?

Thanks,
M.E.

**Comment by nedtwigg** [comment]
Take a look at this:

https://github.com/diffplug/matfilerw/blob/12858a6491e3c46d9cb1585fee5039ef3b79e7f1/src/main/java/com/jmatio/types/MLSparse.java#L52-L80

**Comment by nedtwigg** [comment]
Feel free to reopen if your problem isn't resolved.
