### ISSUE TITLE
Premature MCOS property dereferencing loading

### ISSUE THREAD

**Issue by piotrsmolinski** [diffplug/matfilerw#13]
The MCOS processing routine executes object reference resolution:
https://github.com/diffplug/matfilerw/blob/master/src/main/java/com/jmatio/io/MatFileReader.java#L562-L569

When a reference UINT32 is found, parseMCOS function automatically resolves it. If the reference is an object and has properties, these may have not been processed yet. Therefore processMCOS function may still see incomplete objects. The issue was observed with a struct containing multiple timeseries. The first level references were resolved properly. Second level references (TimeInfo, QualityInfo and DataInfo) were resolved to empty dictionaries.

**Comment by nedtwigg** [comment]
Thanks for the fix!  Published in 3.0.1.
