### ISSUE TITLE
 Limit to the size of memory that the library can read

### ISSUE THREAD

**Issue by SoyeonUm** [diffplug/matfilerw#23]
Hello :)

I want to use this library in android studio to read .mat file in my tablet.

It can read data when the data size is less than about 240MB.

But, when I tried to read data which has more than 280MB, an error occurs.

The error message is 

**

> Process: src.activity, PID: 27325
>     java.lang.OutOfMemoryError: Failed to allocate a 532152336 byte allocation with 25165824 free bytes and 253MB until OOM, max allowed footprint 296141304, growth limit 536870912
>         at java.util.Arrays.copyOf(Arrays.java:3164)
>         at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
>         at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
>         at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
>         at com.jmatio.io.MatFileReader.readData(MatFileReader.java:781)
>         at com.jmatio.io.MatFileReader.parseData(MatFileReader.java:412)
>         at com.jmatio.io.MatFileReader.read(MatFileReader.java:375)
>         at com.jmatio.io.MatFileReader.read(MatFileReader.java:313)
>         at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:174)
>         at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:122)
>         at src.load.Load.loading(Load.java:61)

**

Is there a limit to the size of memory that the library can read? 

Or is there another problem?

I'm sorry if I'm asking stupid questions.

Thank you!

**Comment by nedtwigg** [comment]
This doesn't look like a library limitation, just that your JVM is running out of memory.  I don't know much about android, on desktop you would fix this with something like `-Xmx4g`.

I believe https://github.com/HebiRobotics/MFL is more memory-efficient than this library, so you might have better luck with that.
