### ISSUE TITLE
Eclipse  cannot resolve the annotation @SuppressFBWarnings

### ISSUE THREAD

**Issue by draeger** [diffplug/matfilerw#3]
While the project can be compiled using Gradle, Eclipse still shows warnings for the following import that it cannot resolve:
```Java
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings
```
Where can I find this annotation and how to include it into Eclipse's build path?

**Comment by nedtwigg** [comment]
Did you run `gradlew eclipse`?  This should generate eclipse files with all the necessary deps.

**Comment by draeger** [comment]
Perfect, thanks. Now it works!
