### ISSUE TITLE
Patch for multi-dimensional indexing

### ISSUE THREAD

**Issue by mikaelgrev** [diffplug/matfilerw#4]
Hello,

I might just have misunderstood how to do this but I couldn't figure out how to get a value out of an array with more dimensions than two without using index math. So, I made a .patch to make it simpler. Not sure if you're interested but I have attached it.

If you want this as a pull request instead let me know. Or, if there's a simpler way to do:

array.get(1,3,4,2) to get the element at those indexes also let me know.

Cheers,
Mikael Grev

[multidimindexes.txt](https://github.com/diffplug/matfilerw/files/89458/multidimindexes.txt)

**Comment by nedtwigg** [comment]
A great contribution!  If you submit a PR with some tests, I'll merge it and release as 2.2.0.

**Comment by nedtwigg** [comment]
Thanks for the patch.  I went ahead and applied it along with a trivial patch, released in 2.2.0.  Lemme know if you you'd like any changes in how I [credited you](https://github.com/diffplug/matfilerw/commit/3c74c4d7ddebd8247f59cfa718a66e96d455f9d8).
